tests:
  HaskellExercises-test:
    main:                TastySpec.hs # O el nombre que le hayas dado
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises # El nombre de tu paquete
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - data-rationals